name: test_stardist
channels:
  - defaults
  - nvidia
dependencies:
  - python=3.8
  - cudatoolkit=11.0.*
  - cudnn=8.0.*
  - jupyter
  - numba
  - pandas
  - pip
  - pip:
    - tensorflow==2.4.*
    - csbdeep
    - stardist
